Numpy Crash Course

In [5]:
import numpy as np


In [8]:
np.__version__

'2.3.5'

In [9]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [11]:
type(my_list)


list

In [12]:
ar=np.array(my_list)

In [13]:
type(ar)

numpy.ndarray

In [14]:
ar

array([0, 1, 2, 3, 4, 5])

In [15]:
print(type(my_list))
print(type(ar))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(10,50,5)


array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
np.arang(10,50,5,1)

AttributeError: module 'numpy' has no attribute 'arang'

In [21]:
np.arange(20,10)

array([], dtype=int64)

In [22]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [23]:
np.zeros(3)  #1 d array  (parameter tunning)

array([0., 0., 0.])

In [25]:
np.zeros(3, dtype=int)  #1 d array (hyper parameter tunning)

array([0, 0, 0])

In [30]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [29]:
np.zeros([10,10], dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [34]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [35]:
np.rand(3)

AttributeError: module 'numpy' has no attribute 'rand'

In [38]:
np.random.rand(3)

array([0.26312764, 0.47076702, 0.22478817])

In [40]:
np.random.rand(3,4)

array([[0.39110198, 0.54377339, 0.64457738, 0.50057012],
       [0.41101505, 0.94616693, 0.53236917, 0.17156716],
       [0.09018813, 0.32607256, 0.90212475, 0.67679092]])

In [44]:
np.random.randint(3)

0

In [51]:
np.random.randint(10,15)

12

In [53]:
np.random.randint(10,20,3)

array([14, 17, 10], dtype=int32)

In [55]:
print(np.random.randint(1,10,4))

[2 5 1 7]


In [60]:
m=np.random.randint(1,10,(5,4))
print(m)

[[5 6 5 3]
 [1 5 2 5]
 [1 2 9 6]
 [9 7 6 2]
 [5 7 7 4]]


In [61]:
m=np.random.randint(1,10,(4,6))
print(m)

[[1 4 9 2 1 5]
 [8 7 1 6 1 1]
 [5 6 7 1 2 6]
 [9 6 5 3 4 9]]


In [62]:
m[0]  #first row

array([1, 4, 9, 2, 1, 5], dtype=int32)

In [63]:
m[0]=[4,5,6,7,8,9]  #array manipulation

In [64]:
m

array([[4, 5, 6, 7, 8, 9],
       [8, 7, 1, 6, 1, 1],
       [5, 6, 7, 1, 2, 6],
       [9, 6, 5, 3, 4, 9]], dtype=int32)

In [65]:
m[2]

array([5, 6, 7, 1, 2, 6], dtype=int32)

In [66]:
m[-3]

array([8, 7, 1, 6, 1, 1], dtype=int32)

In [69]:
print(m[0,4])  #specific value print

8


In [70]:
print(m[-2,-3])

1
