In [1]:
import numpy as np

**# 1. Array Creation Function****

In [10]:
#create an array from a list
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [13]:
#create an array with evenly spaced values
b=np.arange(0,10,2)    #values from 0  to 10 with step 2
print ("Array b:",b)

Array b: [0 2 4 6 8]


In [18]:
#create an array filled with zeros
d=np.zeros((2, 3))  # 2X3 array of zeros
print ("Array d: \n",d)

Array d: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
#create an array filled with zeros
d=np.zeros((2, 3), dtype=int)  # 2X3 array of zeros
print ("Array d: \n",d)

Array d: 
 [[0 0 0]
 [0 0 0]]


In [20]:
#create an array filled with ones
e=np.ones((3,2))  # 3X2 matrix
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


2. Array Creation Functions

In [21]:
#Create an identity matrix
f=np.eye(4)  #4X4 identity matrix, 
print("Identity Matrix f:\n",f)

Identity Matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2. Array Manipulation function

In [24]:
#Reshape an array (Rows to column and column to rows)
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3) )
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [ ]:
#Reshape an array (Rows to column and column to rows)
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1) )  # 3 rows and one column
print("Reshaped array:",reshaped)


Reshaped array: [[1]
 [2]
 [3]]


In [ ]:
#Flatten an array       --matrix will convert to linear vector
f1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
Flattened=np.ravel(f1)  #Flatten to 1D array
print("Flattened array:", Flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Transpose an array     --convert rows to columns or vice versa
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)    #Transpose the array
print("Transposed array :\n", transposed)


Transposed array :
 [[1 3]
 [2 4]]


In [34]:
#  Stack arrays Vertically          --np.hstack--horizantal stacking 
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2])      #Stack a and b vertically
print ("Stacked arrays: \n", stacked)


Stacked arrays: 
 [1 2 3 4]


In [35]:
#  Stack arrays Vertically          -- --np.vstack--vertical stacking

a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])      #Stack a and b vertically
print ("Stacked arrays: \n", stacked)

Stacked arrays: 
 [[1 2]
 [3 4]]


3. Mathmatical Functions

In [37]:
#Add two arrays
g=np.array([1,2,3,4])
added=np.add(g,2)       #square each element
print ("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [39]:
#Square each element
g=np.array([1,2,3,4])
squared=np.power(g,2)       #square each element
print ("Squared  2 to g:", squared)

Squared  2 to g: [ 1  4  9 16]


In [41]:
#Square root of each element
sqrt_val=np.sqrt(g)         #Squre root of each element
print("Squrare root of g:", sqrt_val)

Squrare root of g: [1.         1.41421356 1.73205081 2.        ]


In [ ]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [44]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [45]:
a3=np.array([1,2,3])
dot_product=np.dot(a,a1)         # Dot product of a and g
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


4. Statistical Functions

In [47]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print("Mean of s :", mean)

Mean of s : 2.5


In [49]:
s=np.array([1,2,3,4])
var=np.var(s)
print("Variance of s :", var)

Variance of s : 1.25


In [50]:
#Standard deviation of an array
std_dev=np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.118033988749895


In [51]:
s

array([1, 2, 3, 4])

In [52]:
# Minimum element of an array
minimum=np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [53]:
# Maximum element of an array
maximum=np.max(s)
print("Max of s:",maximum)

Max of s: 4


5. Linear Algebra Functions

In [54]:
# Create a matrix
matrix=np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

6. Random Sampling Functions

In [67]:
# Generate random values between 0 and 1
random_vals=np.random.rand(3)       #aRRAY OF 3 RANDOM VALUES BETWEEN 0 AND 1
print("Random Values:",random_vals)

Random Values: [0.38344152 0.79172504 0.52889492]


In [76]:
#Set seed for reporuciblity
np.random.seed(0)

#Generate random values between 0 and 1
random_vals=np.random.rand(3)   # Array of 3 random values between 0 and 1
print("Random integers: ", random_vals)

Random integers:  [0.5488135  0.71518937 0.60276338]


In [87]:
# Generate random integers
rand_ints=np.random.randint(0,10,size=5)
print("Random integer:", rand_ints)

Random integer: [5 9 8 9 4]


In [90]:
#Set seed for reporuciblity

np.random.seed(0)
rand_ints=np.random.randint(0,10,size=5)
print("Random integer:", rand_ints)

Random integer: [5 0 3 3 7]


7. Boolean & Logical Functions

In [92]:
# Check if all elements are True

# all
logical_test=np.array([True,False,True])
all_true=np.all(logical_test) #Check if all are true
print ("All elements True:", all_true)

All elements True: False


In [96]:
# Check if all elements are True

# all
logical_test=np.array([True,False,True])
all_true=np.all(logical_test) #Check if all are true
print ("All elements True:", all_true)

All elements True: False


In [94]:
# Check if all elements are True

# all
logical_test=np.array([False,False,False])
all_true=np.all(logical_test) #Check if all are true
print ("All elements True:", all_true)

All elements True: False


In [97]:
# Check if any  elements are True


all_true=np.any(logical_test) #Check if all are true
print ("Any elements True:", all_true)

Any elements True: True


8. Set Operation


In [99]:
# Intersection of two arrays
set_a=np.array([1,2,3,4])
set_b=np.array([3,5,6,7])
intersection=np.intersect1d(set_a,set_b)
print("Intersection of a and b", intersection)

Intersection of a and b [3]


In [100]:
# Union of two arrays
union=np.union1d(set_a,set_b)
print("Union of a and b", union)

Union of a and b [1 2 3 4 5 6 7]


9. Array Atrribute Function

In [106]:
# Array attributes
a=np.array([1,2,3])
shape=a.shape   #Shape of the array
size=a.size     #Number of elements
dimensions=a.ndim   #Number of Dimensions
dtype=a.dtype       # Data type of the array

print("Shape of a:",shape)
print("Size of a:",size)
print("Number of dimensions of a:",dimensions)
print("Data type of a:",dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


10. Other Functions

In [107]:
# Create a copy of an array
a=np.array([1,2,3])
copied_array=np.copy(a)     # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [108]:
#Size in bytes of an array
array_size_in_bytes=a.nbytes    #size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [ ]:
#Check if two arrays share memory
shared=np.shares_memory(a,copied_array)  # Check if arrays share meomory
print("Do a and copied_arra share memory?", shared)

Do a adn copied_arra share memory? False
